import { ExerciseType } from '@/lib/types';

export const EXERCISE_DATA: Omit<ExerciseType, 'id'>[] = [
  {
    name: 'Air Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayaklarını omuz genişliğinde aç, kalçanı geriye vererek çömel, ardından tekrar ayağa kalk.',
    tips: 'Dizlerin parmak ucunu geçmesin, sırtını dik tut.',
    durationEstimate: 45,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Jump Squat',
    category: 'cardio',
    muscleGroups: ['quadriceps', 'glutes', 'calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Squat pozisyonuna in, yukarıya doğru patlayıcı bir şekilde zıpla ve yumuşak iniş yap.',
    tips: 'Dizlerini korumak için inişte kontrollü ol.',
    durationEstimate: 30,
    caloriesPerMinute: 10,
    isActive: true
  },
  {
    name: 'Pistol Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Tek bacak üzerinde dur, diğer bacağı öne uzat. Kontrollü şekilde çömel ve tekrar ayağa kalk.',
    tips: 'Denge için kollarını önde tut.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Side Lunge',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'adductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayaklarını geniş aç, yana doğru adım atıp çömel, sonra merkeze dön.',
    tips: 'Çömeldiğinde kalçanı geriye gönder.',
    durationEstimate: 40,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Glute Kickback',
    category: 'strength',
    muscleGroups: ['glutes', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Diz ve eller yerde. Bir bacağı yukarıya doğru it, ardından geri indir.',
    tips: 'Hareketi kontrollü yap, belini çukurlaştırma.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Donkey Kick',
    category: 'strength',
    muscleGroups: ['glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Diz ve eller yerde. Dizini 90 derece bükülü tutarak ayağını yukarıya doğru kaldır.',
    tips: 'Üst noktada kalçanı sık.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Fire Hydrant',
    category: 'strength',
    muscleGroups: ['glutes', 'hip abductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Diz ve eller yerde. Bir bacağını yana doğru kaldır, sonra geri indir.',
    tips: 'Kalçanı sabit tutmaya çalış.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Bridge March',
    category: 'strength',
    muscleGroups: ['glutes', 'hamstrings', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Glute bridge pozisyonunda sırayla bir bacağını kaldırıp indir.',
    tips: 'Kalçanı sabit tut, sarkmasına izin verme.',
    durationEstimate: 40,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Bird Dog',
    category: 'strength',
    muscleGroups: ['core', 'glutes', 'lower back'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Eller ve dizler yerde. Sağ kol ve sol bacağı aynı anda uzat, sonra değiştir.',
    tips: 'Belini sabit tut.',
    durationEstimate: 45,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Plank Shoulder Tap',
    category: 'strength',
    muscleGroups: ['core', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Plank pozisyonunda sırayla omuzlarına dokun.',
    tips: 'Kalçanı sabit tut, yana sallanma.',
    durationEstimate: 30,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Side Plank',
    category: 'strength',
    muscleGroups: ['core', 'obliques'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yan tarafa dön, dirseğini yere koy ve kalçanı kaldırarak düz çizgi oluştur.',
    tips: 'Kalçanı aşağı düşürme.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Bicycle Crunch',
    category: 'strength',
    muscleGroups: ['core', 'obliques'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü yat. Ellerini başının arkasına koy, karşı dirseğini karşı dizine doğru getir.',
    tips: 'Boynunu çekiştirme, karın kaslarınla dön.',
    durationEstimate: 40,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Leg Raise',
    category: 'strength',
    muscleGroups: ['core', 'lower abs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü yat, bacaklarını birlikte yukarı kaldır ve yavaşça indir.',
    tips: 'Belini yere sabit tut.',
    durationEstimate: 30,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Flutter Kicks',
    category: 'strength',
    muscleGroups: ['core', 'lower abs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü yat, bacaklarını sırayla hızlıca yukarı-aşağı hareket ettir.',
    tips: 'Alt belini yere bastır.',
    durationEstimate: 30,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Scissor Kicks',
    category: 'strength',
    muscleGroups: ['core', 'lower abs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü yat, bacaklarını çapraz şekilde yukarı-aşağı kesiştirerek hareket ettir.',
    tips: 'Karın kaslarını sıkı tut.',
    durationEstimate: 30,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'V-Up',
    category: 'strength',
    muscleGroups: ['core', 'hip flexors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Sırtüstü yat. Aynı anda bacaklarını ve gövdeni kaldırarak V şekli oluştur.',
    tips: 'Boynunu zorlamadan karın kaslarınla kalk.',
    durationEstimate: 20,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Plank to Push-Up',
    category: 'strength',
    muscleGroups: ['core', 'chest', 'triceps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Dirsek plankından şınav pozisyonuna yüksel, ardından geri in.',
    tips: 'Kalçanı sabit tut.',
    durationEstimate: 30,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Hollow Hold',
    category: 'strength',
    muscleGroups: ['core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü uzan. Omuzlarını ve bacaklarını hafifçe kaldır, belini yere sabit tut.',
    tips: 'Karnını sıkı tut, belini boşluk bırakma.',
    durationEstimate: 20,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Reverse Crunch',
    category: 'strength',
    muscleGroups: ['core', 'lower abs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtüstü yat, dizlerini göğsüne çek ve kalçanı yerden kaldır.',
    tips: 'Hareketi belinden değil karından başlat.',
    durationEstimate: 30,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Inchworm',
    category: 'cardio',
    muscleGroups: ['full_body', 'hamstrings', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayakta dur, ellerini öne doğru yürüterek plank pozisyonuna gel, sonra tekrar ayağa kalk.',
    tips: 'Adımlarını küçük ve kontrollü at.',
    durationEstimate: 40,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Skater Jump',
    category: 'cardio',
    muscleGroups: ['glutes', 'quads', 'calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Yanlara doğru tek ayakla sıçrayarak kaykaycı hareketi yap.',
    tips: 'Dengeyi korumak için kollarını kullan.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  },
  {
    name: 'Jumping Jack',
    category: 'cardio',
    muscleGroups: ['full_body'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Kollar ve bacaklar açık zıplama hareketi yap, sonra kapan.',
    tips: 'Nefesini düzenli tut.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'High Knees',
    category: 'cardio',
    muscleGroups: ['legs', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Olduğun yerde koşarken dizlerini göğsüne doğru kaldır.',
    tips: 'Temponu yüksek tut.',
    durationEstimate: 30,
    caloriesPerMinute: 10,
    isActive: true
  },
  {
    name: 'Butt Kicks',
    category: 'cardio',
    muscleGroups: ['hamstrings', 'calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Olduğun yerde koşarken topuklarını kalçana değdir.',
    tips: 'Dik dur ve tempona odaklan.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Lateral Shuffle',
    category: 'cardio',
    muscleGroups: ['legs', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Hafif çömel pozisyonunda yana doğru hızlı adımlar at.',
    tips: 'Dizlerini hafif bükülü tut.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  },
  {
    name: 'Sprawl',
    category: 'cardio',
    muscleGroups: ['full_body'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Ayakta dur, hızlıca yere kapanıp plank pozisyonuna gel, ardından tekrar ayağa kalk.',
    tips: 'Hareketi patlayıcı yap, ama belini çukurlaştırma.',
    durationEstimate: 30,
    caloriesPerMinute: 11,
    isActive: true
  },
  {
    name: 'Burpee to Tuck Jump',
    category: 'cardio',
    muscleGroups: ['full_body'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Burpee yap ve kalkarken dizlerini göğsüne çekerek zıpla.',
    tips: 'Kollarınla denge sağla.',
    durationEstimate: 30,
    caloriesPerMinute: 13,
    isActive: true
  },
  {
    name: 'Mountain Climber Twist',
    category: 'cardio',
    muscleGroups: ['core', 'obliques', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Plank pozisyonunda dizini çapraz şekilde karşı dirseğe doğru çek.',
    tips: 'Kalçanı sabit tut.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  },
  {
    name: 'Plank Jack',
    category: 'cardio',
    muscleGroups: ['core', 'shoulders', 'legs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Plank pozisyonunda ayaklarını aç-kapat hareketi yap.',
    tips: 'Kalçanı fazla yukarı kaldırma.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Cross-Body Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'triceps', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Şınav yaparken bir dizini karşı dirseğe doğru getir.',
    tips: 'Vücudunu düz tutmaya odaklan.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Diamond Push-Up',
    category: 'strength',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Ellerini göğsünün altında üçgen şekline getirerek şınav yap.',
    tips: 'Dirseklerini fazla açma.',
    durationEstimate: 30,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Decline Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Ayaklarını bir yükseltiye koyarak şınav yap.',
    tips: 'Boynunu nötr pozisyonda tut.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Wide Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ellerini omuz genişliğinden daha açık koyarak şınav yap.',
    tips: 'Dirseklerini fazla bükme.',
    durationEstimate: 30,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Hindu Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps', 'back'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Kalçayı yukarı kaldırıp dalış yapar gibi öne doğru in, ardından yukarı it.',
    tips: 'Hareketi akıcı yap.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  },
  {
    name: 'Dive Bomber Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Pike pozisyonunda öne doğru eğilerek şınav yap, sonra ters hareketle geri dön.',
    tips: 'Belini fazla zorlamadan yap.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  },
  {
    name: 'Hand Release Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Şınavda yere tamamen in, ellerini kaldır ve tekrar it.',
    tips: 'Hareketi kontrollü yap.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Spiderman Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'core', 'obliques'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Şınav yaparken dizini yana doğru dirseğine getir.',
    tips: 'Karın kaslarını sık.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Incline Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Ellerini yüksek bir yüzeye koyarak şınav yap.',
    tips: 'Başını yukarı kaldırma.',
    durationEstimate: 30,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Clap Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 5,
    instructions: 'Şınav yaparken patlayıcı şekilde yukarı it ve ellerini çırp.',
    tips: 'Yere inerken kontrollü ol.',
    durationEstimate: 20,
    caloriesPerMinute: 12,
    isActive: true
  },
  {
    name: 'Archer Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Ellerini geniş aç, ağırlığını bir kola verip şınav yap.',
    tips: 'Hareketi yavaş ve kontrollü yap.',
    durationEstimate: 30,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Plyometric Lunge',
    category: 'cardio',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Lunge pozisyonunda zıpla ve bacak değiştir.',
    tips: 'Dizlerini yumuşak indir.',
    durationEstimate: 30,
    caloriesPerMinute: 10,
    isActive: true
  },
  {
    name: 'Split Squat Jump',
    category: 'cardio',
    muscleGroups: ['quadriceps', 'glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Öne adım at, çömel ve yukarıya doğru zıplayarak bacak değiştir.',
    tips: 'Dengeyi kollarınla sağla.',
    durationEstimate: 30,
    caloriesPerMinute: 11,
    isActive: true
  },
  {
    name: 'Cossack Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'adductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Bacaklarını geniş aç, ağırlığını bir tarafa verip çömel, diğer bacağı düz tut.',
    tips: 'Ayağını yerde sabit tut.',
    durationEstimate: 40,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Wall Sit',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Sırtını duvara yasla ve dizlerini 90 dereceye getirip oturur pozisyonda bekle.',
    tips: 'Dizlerini kilitleme.',
    durationEstimate: 45,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Calf Raise',
    category: 'strength',
    muscleGroups: ['calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Ayakta dik dur, topuklarını kaldırıp tekrar indir.',
    tips: 'Dengeni bozmadan yavaş yap.',
    durationEstimate: 30,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Single-Leg Calf Raise',
    category: 'strength',
    muscleGroups: ['calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Tek ayak üzerinde topuğunu kaldırıp indir.',
    tips: 'Dengeyi sağlamak için duvara tutunabilirsin.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Hip Circles',
    category: 'mobility',
    muscleGroups: ['hips', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Ayakta dur, kalçanı dairesel şekilde döndür.',
    tips: 'Yavaş ve geniş daireler çiz.',
    durationEstimate: 20,
    caloriesPerMinute: 2,
    isActive: true
  },
  {
    name: 'Arm Circles',
    category: 'mobility',
    muscleGroups: ['shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Kollarını yana aç, küçük ve büyük daireler çiz.',
    tips: 'Omuzlarını sabit tut.',
    durationEstimate: 20,
    caloriesPerMinute: 2,
    isActive: true
  },
  {
    name: 'Standing Side Crunch',
    category: 'strength',
    muscleGroups: ['obliques', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Ayakta kollarını başının üstünde tut, dirseğini dizine doğru yana çek.',
    tips: 'Karın kaslarını sıkı tut.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Standing Knee to Elbow',
    category: 'cardio',
    muscleGroups: ['core', 'legs'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Ayakta karşı dirseğini karşı dizine doğru getir.',
    tips: 'Ritmik yap.',
    durationEstimate: 30,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Lying Side Leg Lift',
    category: 'strength',
    muscleGroups: ['glutes', 'hip abductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Yan yat, üstteki bacağını yukarı kaldırıp indir.',
    tips: 'Hareketi yavaş yap.',
    durationEstimate: 30,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Lying Inner Thigh Lift',
    category: 'strength',
    muscleGroups: ['adductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Yan yat, alttaki bacağını öne çıkararak yukarı kaldır.',
    tips: 'Karın kaslarını sıkı tut.',
    durationEstimate: 30,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Reverse Lunge',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayakta dur, bir adımı geriye atarak lunge yap ve geri dön.',
    tips: 'Öndeki dizin parmak ucunu geçmesin.',
    durationEstimate: 40,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Curtsy Lunge',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'adductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayakta dur, bir bacağını çapraz arkaya atarak çömel.',
    tips: 'Kalçanı geriye gönder.',
    durationEstimate: 40,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Step Back Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Squat pozisyonuna in, bir bacağını geriye adım atıp tekrar merkeze dön.',
    tips: 'Sırtını dik tut.',
    durationEstimate: 30,
    caloriesPerMinute: 6,
    isActive: true
  },
  {
    name: 'Wall Push-Up',
    category: 'strength',
    muscleGroups: ['chest', 'triceps', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Duvara dön, ellerini omuz hizasında koyarak şınav yap.',
    tips: 'Kontrollü in ve çık.',
    durationEstimate: 30,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Superman Hold',
    category: 'strength',
    muscleGroups: ['lower back', 'glutes', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yüzüstü uzan, kollarını ve bacaklarını aynı anda kaldır.',
    tips: 'Belini zorlamadan kısa süre tut.',
    durationEstimate: 20,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Swimmer',
    category: 'strength',
    muscleGroups: ['lower back', 'glutes', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yüzüstü uzan, sağ kol ve sol bacağı kaldır, sonra değiştir.',
    tips: 'Küçük ama kontrollü hareketler yap.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Prone Y Raise',
    category: 'strength',
    muscleGroups: ['shoulders', 'upper back'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yüzüstü uzan, kollarını Y şeklinde kaldır.',
    tips: 'Omuzlarını sıkıştır.',
    durationEstimate: 20,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Prone T Raise',
    category: 'strength',
    muscleGroups: ['rear delts', 'upper back'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yüzüstü uzan, kollarını T şeklinde yana kaldır.',
    tips: 'Kürek kemiklerini sıkıştır.',
    durationEstimate: 20,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Prone W Raise',
    category: 'strength',
    muscleGroups: ['rear delts', 'traps'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Yüzüstü uzan, dirseklerini büküp W şekli oluştur ve kollarını kaldır.',
    tips: 'Kontrollü yap.',
    durationEstimate: 20,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Bear Crawl',
    category: 'cardio',
    muscleGroups: ['full_body', 'core', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Dizler yerde ama havada, eller ve ayaklarla ileri geri yürü.',
    tips: 'Core kaslarını sıkı tut.',
    durationEstimate: 40,
    caloriesPerMinute: 8,
    isActive: true
  },
  {
    name: 'Crab Walk',
    category: 'cardio',
    muscleGroups: ['shoulders', 'glutes', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Eller ve ayaklarla ters köprüde yürümeye başla.',
    tips: 'Kalçanı düşürme.',
    durationEstimate: 40,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Duck Walk',
    category: 'cardio',
    muscleGroups: ['quads', 'glutes'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Çömel pozisyonunda kısa adımlarla öne doğru yürü.',
    tips: 'Dizlerini zorlamadan yap.',
    durationEstimate: 30,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Broad Jump',
    category: 'cardio',
    muscleGroups: ['quads', 'glutes', 'calves'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Çömel, ileriye doğru patlayıcı bir sıçrama yap.',
    tips: 'Yumuşak iniş yap.',
    durationEstimate: 20,
    caloriesPerMinute: 10,
    isActive: true
  },
  {
    name: 'Tuck Jump',
    category: 'cardio',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 4,
    instructions: 'Zıplarken dizlerini göğsüne çek.',
    tips: 'Yumuşak iniş yap.',
    durationEstimate: 20,
    caloriesPerMinute: 11,
    isActive: true
  },
  {
    name: 'Lunge with Knee Drive',
    category: 'strength',
    muscleGroups: ['quads', 'glutes', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Lunge pozisyonuna in, ayağa kalkarken öndeki bacağını yukarı diz sürüşü yap.',
    tips: 'Dengen için core kaslarını sıkı tut.',
    durationEstimate: 30,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Side Leg Pulse',
    category: 'strength',
    muscleGroups: ['glutes', 'hip abductors'],
    equipmentNeeded: ['none'],
    difficultyLevel: 1,
    instructions: 'Yan yat, üst bacağını hafif kaldırıp küçük titreşimlerle hareket ettir.',
    tips: 'Kalçanı sabit tut.',
    durationEstimate: 30,
    caloriesPerMinute: 3,
    isActive: true
  },
  {
    name: 'Reverse Plank',
    category: 'strength',
    muscleGroups: ['glutes', 'core', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ellerini arkana koyarak otur, kalçanı yukarı kaldır ve düz çizgi oluştur.',
    tips: 'Boynunu rahat bırak.',
    durationEstimate: 30,
    caloriesPerMinute: 4,
    isActive: true
  },
  {
    name: 'Reverse Plank Leg Lift',
    category: 'strength',
    muscleGroups: ['glutes', 'core', 'hamstrings'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Reverse plank pozisyonunda bir bacağını kaldırıp indir.',
    tips: 'Kalçanı sabit tut.',
    durationEstimate: 30,
    caloriesPerMinute: 5,
    isActive: true
  },
  {
    name: 'Crawl Out',
    category: 'cardio',
    muscleGroups: ['core', 'shoulders'],
    equipmentNeeded: ['none'],
    difficultyLevel: 2,
    instructions: 'Ayakta dur, öne eğilip ellerinle plank pozisyonuna git, sonra geri gel.',
    tips: 'Belini düz tut.',
    durationEstimate: 40,
    caloriesPerMinute: 7,
    isActive: true
  },
  {
    name: 'Side Shuffle with Floor Tap',
    category: 'cardio',
    muscleGroups: ['legs', 'core'],
    equipmentNeeded: ['none'],
    difficultyLevel: 3,
    instructions: 'Yana doğru shuffle yaparken yere dokun.',
    tips: 'Kalçanı alçak tut.',
    durationEstimate: 30,
    caloriesPerMinute: 9,
    isActive: true
  }
];
